// =============================================================================
// STF/STJ Precedent Monitor
// Auto-updating tracker for Supreme Court and Superior Court decisions,
// binding precedents, repetitive themes, and repercussao geral.
// =============================================================================
//
// This module monitors:
// - STF voting sessions (Plenario and Turmas)
// - STJ repetitive themes (recursos repetitivos)
// - New sumulas and sumulas vinculantes
// - Repercussao geral themes and their status
// - Informativos (weekly case law bulletins)
//
// The monitor runs periodically (configurable) and generates notifications
// when new precedents are published that may affect the user's cases.
// =============================================================================

import {
  CourtAdapterError,
  DEFAULT_RETRY_CONFIG,
  withRetry,
} from '@/lib/court/court-adapter';

import type { RetryConfig } from '@/lib/court/court-adapter';

// ─── Configuration ──────────────────────────────────────────────────────────

interface MonitorConfig {
  stfApiUrl: string;
  stjApiUrl: string;
  timeoutMs: number;
  retry: RetryConfig;
  /** Polling interval in milliseconds (default: 1 hour) */
  pollingIntervalMs: number;
}

const DEFAULT_MONITOR_CONFIG: MonitorConfig = {
  stfApiUrl: process.env.STF_API_URL || 'https://portal.stf.jus.br/api/v1',
  stjApiUrl: process.env.STJ_API_URL || 'https://processo.stj.jus.br/api/v1',
  timeoutMs: 30000,
  retry: DEFAULT_RETRY_CONFIG,
  pollingIntervalMs: 3600000, // 1 hour
};

// ─── Types ──────────────────────────────────────────────────────────────────

/** A monitored STF voting session */
export interface STFVotingSession {
  id: string;
  type: 'plenario' | 'primeira_turma' | 'segunda_turma' | 'plenario_virtual';
  date: string;
  status: 'scheduled' | 'in_progress' | 'completed' | 'adjourned';
  cases: STFCaseOnAgenda[];
}

export interface STFCaseOnAgenda {
  id: string;
  caseNumber: string;
  caseType: string;
  relator: string;
  subject: string;
  repercussaoGeral?: {
    themeNumber: number;
    themeTitle: string;
  };
  result?: STFVotingResult;
}

export interface STFVotingResult {
  decision: string;
  votes: STFVote[];
  votingDate: string;
  isUnanimous: boolean;
}

export interface STFVote {
  minister: string;
  vote: 'provido' | 'desprovido' | 'parcialmente_provido' | 'ausente' | 'impedido';
  hasWrittenVote: boolean;
}

/** A repercussao geral theme tracked by the monitor */
export interface RepercussaoGeralTheme {
  themeNumber: number;
  title: string;
  description: string;
  status: 'pending' | 'recognized' | 'not_recognized' | 'decided' | 'thesis_fixed';
  leadingCase: string;
  relator: string;
  recognitionDate?: string;
  decisionDate?: string;
  thesis?: string;
  affectedProcessCount?: number;
}

/** An STJ repetitive theme (recurso repetitivo) */
export interface STJRepetitiveTheme {
  themeNumber: number;
  title: string;
  description: string;
  status: 'affected' | 'judged' | 'thesis_fixed' | 'transited';
  leadingCases: string[];
  relator: string;
  affectedDate?: string;
  judgmentDate?: string;
  thesis?: string;
  affectedCourt?: string;
}

/** A sumula or sumula vinculante */
export interface SumulaUpdate {
  id: string;
  number: number;
  court: 'STF' | 'STJ';
  type: 'sumula' | 'sumula_vinculante';
  text: string;
  approvalDate: string;
  publicationDate: string;
  status: 'active' | 'revised' | 'cancelled';
  references: string[];
}

/** An informativo (weekly case law bulletin) */
export interface Informativo {
  id: string;
  number: number;
  court: 'STF' | 'STJ';
  title: string;
  period: string;
  publishedAt: string;
  entries: InformativoEntry[];
}

export interface InformativoEntry {
  id: string;
  caseNumber: string;
  subject: string;
  summary: string;
  themes: string[];
  relator: string;
}

/** Notification generated by the monitor */
export interface PrecedentNotification {
  id: string;
  type: PrecedentNotificationType;
  title: string;
  description: string;
  source: 'STF' | 'STJ';
  date: string;
  severity: 'high' | 'medium' | 'low';
  relatedThemes: string[];
  url?: string;
  isRead: boolean;
}

export type PrecedentNotificationType =
  | 'new_decision'
  | 'thesis_fixed'
  | 'new_sumula'
  | 'repercussao_geral'
  | 'repetitive_theme'
  | 'informativo'
  | 'voting_session';

/** Subscription filter for notifications */
export interface MonitorSubscription {
  id: string;
  /** Themes to watch (matched against decision themes) */
  themes: string[];
  /** Legal areas of interest */
  areas: string[];
  /** Specific case numbers to track */
  caseNumbers: string[];
  /** Minimum notification severity */
  minSeverity: 'high' | 'medium' | 'low';
  /** Whether to track STF decisions */
  trackSTF: boolean;
  /** Whether to track STJ decisions */
  trackSTJ: boolean;
  /** Whether to track repercussao geral */
  trackRepercussaoGeral: boolean;
  /** Whether to track recursos repetitivos */
  trackRepetitivos: boolean;
  /** Whether to track new sumulas */
  trackSumulas: boolean;
  /** Whether to track informativos */
  trackInformativos: boolean;
}

// ─── Mock Data ──────────────────────────────────────────────────────────────

const MOCK_RG_THEMES: RepercussaoGeralTheme[] = [
  {
    themeNumber: 786,
    title: 'Dano moral e quantum indenizatorio em relacoes de consumo',
    description: 'Limites constitucionais para fixacao de indenizacao por dano moral decorrente de relacao de consumo.',
    status: 'thesis_fixed',
    leadingCase: 'RE 1.234.567/SP',
    relator: 'Min. Luis Roberto Barroso',
    recognitionDate: '2023-06-15',
    decisionDate: '2024-09-15',
    thesis: 'O quantum indenizatorio por dano moral em relacoes de consumo deve observar os principios da razoabilidade e proporcionalidade, sendo vedada a fixacao de valores irrisorios que descaracterizem a funcao reparatoria.',
    affectedProcessCount: 45000,
  },
  {
    themeNumber: 1246,
    title: 'Responsabilidade civil do Estado por omissao em saude publica',
    description: 'Responsabilidade civil do Estado por falha na prestacao de servicos de saude publica, incluindo falta de medicamentos e leitos.',
    status: 'recognized',
    leadingCase: 'RE 1.345.678/MG',
    relator: 'Min. Alexandre de Moraes',
    recognitionDate: '2024-03-20',
    affectedProcessCount: 120000,
  },
  {
    themeNumber: 1300,
    title: 'Limites da liberdade de expressao em redes sociais',
    description: 'Definicao dos limites constitucionais da liberdade de expressao em plataformas digitais e redes sociais, especialmente quanto a moderacao de conteudo.',
    status: 'pending',
    leadingCase: 'RE 1.456.789/DF',
    relator: 'Min. Dias Toffoli',
  },
];

const MOCK_STJ_REPETITIVOS: STJRepetitiveTheme[] = [
  {
    themeNumber: 952,
    title: 'Contrato bancario - Revisao de juros remuneratorios',
    description: 'Definicao dos parametros para revisao judicial de juros remuneratorios em contratos bancarios, inclusive quanto a abusividade.',
    status: 'thesis_fixed',
    leadingCases: ['REsp 1.061.530/RS', 'REsp 1.112.879/PR'],
    relator: 'Min. Nancy Andrighi',
    affectedDate: '2022-10-15',
    judgmentDate: '2024-02-20',
    thesis: 'As instituicoes financeiras nao se sujeitam a limitacao de juros prevista no Decreto 22.626/33 (Sumula 596/STF). A abusividade dos juros deve ser analisada caso a caso, devendo ser considerada a taxa media de mercado praticada pelo Banco Central.',
  },
  {
    themeNumber: 1101,
    title: 'IRPF sobre juros moratorios em acoes trabalhistas',
    description: 'Incidencia de imposto de renda sobre juros moratorios recebidos em reclamatorias trabalhistas.',
    status: 'judged',
    leadingCases: ['REsp 1.470.443/PR'],
    relator: 'Min. Mauro Campbell Marques',
    affectedDate: '2023-05-10',
    judgmentDate: '2024-06-15',
  },
];

const MOCK_NOTIFICATIONS: PrecedentNotification[] = [
  {
    id: 'notif-001',
    type: 'thesis_fixed',
    title: 'STF fixa tese sobre dano moral em relacoes de consumo (Tema 786)',
    description: 'O Plenario do STF fixou a tese de repercussao geral no Tema 786, estabelecendo que o quantum indenizatorio por dano moral em relacoes de consumo deve observar os principios da razoabilidade e proporcionalidade.',
    source: 'STF',
    date: '2024-09-15',
    severity: 'high',
    relatedThemes: ['dano moral', 'consumidor', 'quantum indenizatorio'],
    url: 'https://portal.stf.jus.br/temas/786',
    isRead: false,
  },
  {
    id: 'notif-002',
    type: 'repetitive_theme',
    title: 'STJ julga recurso repetitivo sobre juros bancarios (Tema 952)',
    description: 'A Segunda Secao do STJ julgou o Tema 952 sobre revisao de juros remuneratorios em contratos bancarios, reafirmando a Sumula 596/STF.',
    source: 'STJ',
    date: '2024-02-20',
    severity: 'high',
    relatedThemes: ['contrato bancario', 'juros', 'revisao contratual'],
    url: 'https://processo.stj.jus.br/repetitivos/952',
    isRead: false,
  },
  {
    id: 'notif-003',
    type: 'informativo',
    title: 'Informativo STJ 830 - Novas decisoes em direito civil e processual',
    description: 'O Informativo 830 traz decisoes sobre responsabilidade civil, direito do consumidor e direito processual civil.',
    source: 'STJ',
    date: '2024-11-15',
    severity: 'medium',
    relatedThemes: ['responsabilidade civil', 'consumidor', 'processual civil'],
    isRead: false,
  },
];

// ─── STF/STJ Monitor Implementation ────────────────────────────────────────

/**
 * Auto-updating precedent tracker for STF and STJ decisions.
 *
 * Monitors:
 * - STF voting sessions and decisions (Plenario and Turmas)
 * - STJ repetitive themes (recursos repetitivos)
 * - New sumulas and sumulas vinculantes
 * - Repercussao geral themes and thesis fixation
 * - Weekly informativos from both courts
 *
 * Generates notifications when new precedents match subscribed themes.
 *
 * @example
 * ```typescript
 * const monitor = new STFSTJMonitor();
 *
 * // Subscribe to themes
 * monitor.subscribe({
 *   id: 'sub-001',
 *   themes: ['dano moral', 'consumidor'],
 *   areas: ['civil', 'consumidor'],
 *   caseNumbers: [],
 *   minSeverity: 'medium',
 *   trackSTF: true,
 *   trackSTJ: true,
 *   trackRepercussaoGeral: true,
 *   trackRepetitivos: true,
 *   trackSumulas: true,
 *   trackInformativos: true,
 * });
 *
 * // Check for new notifications
 * const notifications = await monitor.getNotifications();
 * ```
 */
export class STFSTJMonitor {
  private config: MonitorConfig;
  private subscriptions: MonitorSubscription[] = [];
  private notifications: PrecedentNotification[] = [];
  private lastCheckTime: number = 0;
  private useMockData: boolean;

  constructor(config?: Partial<MonitorConfig>) {
    this.config = { ...DEFAULT_MONITOR_CONFIG, ...config };
    this.useMockData = process.env.NODE_ENV === 'development' || !process.env.STF_API_URL;
    this.notifications = [...MOCK_NOTIFICATIONS];
  }

  // ─── Subscription Management ──────────────────────────────────────────────

  /**
   * Subscribe to precedent notifications matching the given criteria.
   *
   * @param subscription - Subscription configuration
   */
  subscribe(subscription: MonitorSubscription): void {
    const existing = this.subscriptions.findIndex((s) => s.id === subscription.id);
    if (existing >= 0) {
      this.subscriptions[existing] = subscription;
    } else {
      this.subscriptions.push(subscription);
    }
  }

  /**
   * Remove a subscription.
   *
   * @param subscriptionId - The subscription to remove
   */
  unsubscribe(subscriptionId: string): void {
    this.subscriptions = this.subscriptions.filter((s) => s.id !== subscriptionId);
  }

  /**
   * Get all active subscriptions.
   */
  getSubscriptions(): MonitorSubscription[] {
    return [...this.subscriptions];
  }

  // ─── Notifications ────────────────────────────────────────────────────────

  /**
   * Get all pending (unread) notifications.
   * Optionally filters by subscription themes.
   *
   * @param unreadOnly - Only return unread notifications (default: true)
   * @returns Array of notifications
   */
  async getNotifications(unreadOnly: boolean = true): Promise<PrecedentNotification[]> {
    // Check if it's time to poll for new precedents
    const now = Date.now();
    if (now - this.lastCheckTime > this.config.pollingIntervalMs) {
      await this.checkForUpdates();
      this.lastCheckTime = now;
    }

    let filtered = [...this.notifications];

    if (unreadOnly) {
      filtered = filtered.filter((n) => !n.isRead);
    }

    // Filter by subscriptions
    if (this.subscriptions.length > 0) {
      filtered = filtered.filter((n) => this.matchesAnySubscription(n));
    }

    return filtered.sort(
      (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime(),
    );
  }

  /**
   * Mark a notification as read.
   */
  markAsRead(notificationId: string): void {
    const notif = this.notifications.find((n) => n.id === notificationId);
    if (notif) {
      notif.isRead = true;
    }
  }

  /**
   * Mark all notifications as read.
   */
  markAllAsRead(): void {
    for (const notif of this.notifications) {
      notif.isRead = true;
    }
  }

  // ─── Repercussao Geral ────────────────────────────────────────────────────

  /**
   * Get repercussao geral themes from the STF.
   *
   * Repercussao geral is a mechanism where the STF selects cases of
   * general significance and issues binding precedents that apply to
   * all similar cases nationwide.
   *
   * @param status - Filter by theme status
   * @returns Array of repercussao geral themes
   */
  async getRepercussaoGeralThemes(
    status?: RepercussaoGeralTheme['status'],
  ): Promise<RepercussaoGeralTheme[]> {
    if (this.useMockData) {
      return status
        ? MOCK_RG_THEMES.filter((t) => t.status === status)
        : MOCK_RG_THEMES;
    }

    return withRetry(async () => {
      const params = new URLSearchParams();
      if (status) params.set('status', status);

      const response = await fetch(
        `${this.config.stfApiUrl}/repercussao-geral/temas?${params.toString()}`,
        {
          headers: { 'Accept': 'application/json' },
          signal: AbortSignal.timeout(this.config.timeoutMs),
        },
      );

      if (!response.ok) {
        throw new CourtAdapterError(
          `Failed to fetch RG themes: HTTP ${response.status}`,
          'datajud',
          'SYSTEM_UNAVAILABLE',
          response.status,
          true,
        );
      }

      return (await response.json()) as RepercussaoGeralTheme[];
    }, this.config.retry);
  }

  // ─── STJ Repetitive Themes ────────────────────────────────────────────────

  /**
   * Get STJ repetitive themes (recursos repetitivos).
   *
   * Recursos repetitivos are a mechanism where the STJ selects representative
   * cases for themes that generate a high volume of similar appeals. The
   * decision on the representative case binds all similar cases.
   *
   * @param status - Filter by theme status
   * @returns Array of repetitive themes
   */
  async getRepetitiveThemes(
    status?: STJRepetitiveTheme['status'],
  ): Promise<STJRepetitiveTheme[]> {
    if (this.useMockData) {
      return status
        ? MOCK_STJ_REPETITIVOS.filter((t) => t.status === status)
        : MOCK_STJ_REPETITIVOS;
    }

    return withRetry(async () => {
      const params = new URLSearchParams();
      if (status) params.set('status', status);

      const response = await fetch(
        `${this.config.stjApiUrl}/repetitivos/temas?${params.toString()}`,
        {
          headers: { 'Accept': 'application/json' },
          signal: AbortSignal.timeout(this.config.timeoutMs),
        },
      );

      if (!response.ok) {
        throw new CourtAdapterError(
          `Failed to fetch repetitive themes: HTTP ${response.status}`,
          'datajud',
          'SYSTEM_UNAVAILABLE',
          response.status,
          true,
        );
      }

      return (await response.json()) as STJRepetitiveTheme[];
    }, this.config.retry);
  }

  // ─── STF Voting Sessions ──────────────────────────────────────────────────

  /**
   * Get upcoming and recent STF voting sessions.
   *
   * @param type - Filter by session type
   * @returns Array of voting sessions
   */
  async getVotingSessions(
    type?: STFVotingSession['type'],
  ): Promise<STFVotingSession[]> {
    if (this.useMockData) {
      return this.mockVotingSessions(type);
    }

    return withRetry(async () => {
      const params = new URLSearchParams();
      if (type) params.set('type', type);

      const response = await fetch(
        `${this.config.stfApiUrl}/pautas?${params.toString()}`,
        {
          headers: { 'Accept': 'application/json' },
          signal: AbortSignal.timeout(this.config.timeoutMs),
        },
      );

      if (!response.ok) {
        throw new CourtAdapterError(
          `Failed to fetch voting sessions: HTTP ${response.status}`,
          'datajud',
          'SYSTEM_UNAVAILABLE',
          response.status,
          true,
        );
      }

      return (await response.json()) as STFVotingSession[];
    }, this.config.retry);
  }

  // ─── Informativos ─────────────────────────────────────────────────────────

  /**
   * Get recent informativos (weekly case law bulletins) from STF or STJ.
   *
   * @param court - Court filter
   * @param limit - Maximum number of informativos to return
   * @returns Array of informativos
   */
  async getInformativos(
    court?: 'STF' | 'STJ',
    limit: number = 5,
  ): Promise<Informativo[]> {
    if (this.useMockData) {
      return this.mockInformativos(court, limit);
    }

    const apiUrl = court === 'STF' ? this.config.stfApiUrl : this.config.stjApiUrl;

    return withRetry(async () => {
      const response = await fetch(
        `${apiUrl}/informativos?limit=${limit}`,
        {
          headers: { 'Accept': 'application/json' },
          signal: AbortSignal.timeout(this.config.timeoutMs),
        },
      );

      if (!response.ok) {
        throw new CourtAdapterError(
          `Failed to fetch informativos: HTTP ${response.status}`,
          'datajud',
          'SYSTEM_UNAVAILABLE',
          response.status,
          true,
        );
      }

      return (await response.json()) as Informativo[];
    }, this.config.retry);
  }

  // ─── Private Helpers ──────────────────────────────────────────────────────

  /**
   * Check for updates from STF and STJ.
   * Called periodically based on the polling interval.
   */
  private async checkForUpdates(): Promise<void> {
    if (this.useMockData) return;

    try {
      // Check STF for new decisions and voting results
      const stfSessions = await this.getVotingSessions();
      for (const session of stfSessions) {
        if (session.status === 'completed') {
          for (const caseItem of session.cases) {
            if (caseItem.result) {
              this.addNotificationIfNew({
                id: `notif-stf-${caseItem.id}`,
                type: 'new_decision',
                title: `STF decidiu: ${caseItem.caseNumber}`,
                description: `${caseItem.subject} - ${caseItem.result.decision}`,
                source: 'STF',
                date: session.date,
                severity: caseItem.repercussaoGeral ? 'high' : 'medium',
                relatedThemes: [caseItem.subject],
                isRead: false,
              });
            }
          }
        }
      }

      // Check for new repercussao geral themes
      const rgThemes = await this.getRepercussaoGeralThemes('thesis_fixed');
      for (const theme of rgThemes) {
        this.addNotificationIfNew({
          id: `notif-rg-${theme.themeNumber}`,
          type: 'thesis_fixed',
          title: `Tese fixada - Tema ${theme.themeNumber}: ${theme.title}`,
          description: theme.thesis || theme.description,
          source: 'STF',
          date: theme.decisionDate || new Date().toISOString(),
          severity: 'high',
          relatedThemes: [theme.title],
          isRead: false,
        });
      }
    } catch {
      // Silently fail - will retry on next poll
    }
  }

  /**
   * Add a notification only if one with the same ID doesn't already exist.
   */
  private addNotificationIfNew(notification: PrecedentNotification): void {
    if (!this.notifications.find((n) => n.id === notification.id)) {
      this.notifications.push(notification);
    }
  }

  /**
   * Check if a notification matches any active subscription.
   */
  private matchesAnySubscription(notification: PrecedentNotification): boolean {
    if (this.subscriptions.length === 0) return true;

    return this.subscriptions.some((sub) => {
      // Check court filter
      if (notification.source === 'STF' && !sub.trackSTF) return false;
      if (notification.source === 'STJ' && !sub.trackSTJ) return false;

      // Check type filters
      if (notification.type === 'repercussao_geral' && !sub.trackRepercussaoGeral) return false;
      if (notification.type === 'repetitive_theme' && !sub.trackRepetitivos) return false;
      if (notification.type === 'new_sumula' && !sub.trackSumulas) return false;
      if (notification.type === 'informativo' && !sub.trackInformativos) return false;

      // Check severity
      const severityOrder = { high: 3, medium: 2, low: 1 };
      if (severityOrder[notification.severity] < severityOrder[sub.minSeverity]) return false;

      // Check theme overlap
      if (sub.themes.length > 0) {
        const hasThemeMatch = sub.themes.some((theme) =>
          notification.relatedThemes.some((nt) =>
            nt.toLowerCase().includes(theme.toLowerCase()),
          ),
        );
        if (!hasThemeMatch) return false;
      }

      return true;
    });
  }

  // ─── Mock Implementations ─────────────────────────────────────────────────

  private mockVotingSessions(type?: STFVotingSession['type']): STFVotingSession[] {
    const sessions: STFVotingSession[] = [
      {
        id: 'session-001',
        type: 'plenario',
        date: '2024-11-20',
        status: 'completed',
        cases: [
          {
            id: 'case-stf-001',
            caseNumber: 'ADI 7.123/DF',
            caseType: 'Acao Direta de Inconstitucionalidade',
            relator: 'Min. Gilmar Mendes',
            subject: 'Constitucionalidade de lei estadual sobre ICMS',
            result: {
              decision: 'Julgada procedente para declarar a inconstitucionalidade',
              votes: [
                { minister: 'Min. Gilmar Mendes', vote: 'provido', hasWrittenVote: true },
                { minister: 'Min. Luis Roberto Barroso', vote: 'provido', hasWrittenVote: false },
                { minister: 'Min. Alexandre de Moraes', vote: 'provido', hasWrittenVote: false },
              ],
              votingDate: '2024-11-20',
              isUnanimous: true,
            },
          },
        ],
      },
      {
        id: 'session-002',
        type: 'plenario_virtual',
        date: '2024-11-22',
        status: 'in_progress',
        cases: [
          {
            id: 'case-stf-002',
            caseNumber: 'RE 1.456.789/DF',
            caseType: 'Recurso Extraordinario',
            relator: 'Min. Dias Toffoli',
            subject: 'Limites da liberdade de expressao em redes sociais',
            repercussaoGeral: {
              themeNumber: 1300,
              themeTitle: 'Limites da liberdade de expressao em redes sociais',
            },
          },
        ],
      },
    ];

    return type ? sessions.filter((s) => s.type === type) : sessions;
  }

  private mockInformativos(court?: 'STF' | 'STJ', limit: number = 5): Informativo[] {
    const informativos: Informativo[] = [
      {
        id: 'inf-stj-830',
        number: 830,
        court: 'STJ',
        title: 'Informativo de Jurisprudencia n. 830',
        period: '04/11/2024 a 08/11/2024',
        publishedAt: '2024-11-15',
        entries: [
          {
            id: 'entry-001',
            caseNumber: 'REsp 2.100.000/SP',
            subject: 'Responsabilidade civil por dano moral em comercio eletronico',
            summary: 'O fornecedor de marketplace responde solidariamente por danos causados ao consumidor por vendedor cadastrado na plataforma.',
            themes: ['responsabilidade civil', 'marketplace', 'consumidor'],
            relator: 'Min. Nancy Andrighi',
          },
          {
            id: 'entry-002',
            caseNumber: 'REsp 2.150.000/RS',
            subject: 'Prescricao em acao de cobranca de honorarios advocaticios',
            summary: 'O prazo prescricional para cobranca de honorarios advocaticios contratuais e de 5 anos (art. 206, par. 5o, II, CC).',
            themes: ['honorarios', 'prescricao', 'advocacia'],
            relator: 'Min. Marco Buzzi',
          },
        ],
      },
      {
        id: 'inf-stf-1125',
        number: 1125,
        court: 'STF',
        title: 'Informativo STF n. 1125',
        period: '28/10/2024 a 01/11/2024',
        publishedAt: '2024-11-08',
        entries: [
          {
            id: 'entry-003',
            caseNumber: 'ADI 7.200/DF',
            subject: 'Competencia legislativa em materia tributaria',
            summary: 'Estados nao podem criar obrigacoes acessorias que extrapolem sua competencia tributaria.',
            themes: ['tributario', 'competencia legislativa', 'federalismo'],
            relator: 'Min. Alexandre de Moraes',
          },
        ],
      },
    ];

    let filtered = court ? informativos.filter((i) => i.court === court) : informativos;
    return filtered.slice(0, limit);
  }
}
